- app/main/views/corpus.py
- app/models/linguistic.py
- app/templates/macros/tokens_macros.html
- app/templates/main/corpus_new.html
- tests/test_selenium/test_corpus_init.py
Add an option to specify the context setting
> Context setting

- app/models/linguistic.py
- tests/test_selenium/base.py
- tests/test_selenium/test_token_edit.py
> Auto complete pour AllowedMorph sur valeurs comme sur label

- app/main/views/tokens.py
- app/models/linguistic.py
- tests/test_cli/test_corpus.py
Cela ne fixe pas tout (notamment la page d'accueil) mais cela réduit le temps de création d'un corpus au moins...
> Performance fix : Creation de corpus

- app/main/views/utils.py
- app/models/linguistic.py
- app/utils/tsv.py
- tests/test_cli/test_corpus.py
- tests/test_selenium/test_corpus_init.py
> Quotation mark are removed from input and cause issues in reading TSV

- app/main/views/corpus.py
- app/main/views/tokens.py
- app/models/corpus.py
- app/templates/main/corpus_new.html
- app/templates/main/tokens_view.html
- app/templates/tei/geste.xml
- tests/db_fixtures/__init__.py
- tests/test_selenium/base.py
- tests/test_selenium/test_corpus_init.py
- tests/test_selenium/test_export.py
> Add a delimiter token to corpus configuration

- app/main/views/corpus.py
- app/main/views/tokens.py
- app/models/corpus.py
- tests/test_selenium/test_corpus_init.py
CC @MrGecko pour corriger l'export depuis la version actuelle de PPA
> Small fix for export

- app/main/views/tokens.py
- app/templates/macros/tokens_macros.html
- app/templates/main/corpus_new.html
- tests/test_selenium/test_tokens_search_through_fields.py
Fixes #113 
Fixes #116 [ Except last token ]
Fixes #115
> Various fixes

- app/control_lists/forms.py
- app/control_lists/views.py
- app/templates/control_lists/macros.html
- app/templates/control_lists/rename.html
- tests/test_selenium/test_control_lists.py
> Add the ability to rename a control list

- app/main/forms.py
- app/main/views/corpus.py
- app/main/views/utils.py
- app/models/corpus.py
- app/templates/layouts/base.html
- app/templates/macros/nav_macros.html
- app/templates/main/corpus_delete.html
Fixed #99
Pas de tests. Il faudrait vérifier que rien n'est perdu dans les autres tables, je suis pas SUPER confiant dans mes backref et cascade....
> Ability to delete the corpus

- app/models/corpus.py
With this patch it is ~8x faster to load the "correct tokens" page on my local instance .
> Correct token perf

- app/main/views/corpus.py
- app/models/corpus.py
- app/statics/css/site.css
- app/templates/macros/nav_macros.html
- app/templates/main/corpus_info.html
> Nicer home for corpora

- .travis.yml
Try to dynamically set up the driver version using the version of the installed chrome browser (fixes #186)
> Automatically match the driver version with the browser version

- app/models/control_lists.py
> fix for #193

- app/models/control_lists.py
- requirements.txt
Werkzeug > 1.0.1 bugs on Windows 10
> fix for Windows bug

- app/templates/control_lists/edit.html
- app/templates/macros/upload_text.html
- app/templates/main/corpus_new.html
- tests/test_selenium/base.py
- tests/test_selenium/test_control_lists.py
- tests/test_selenium/test_corpus_init.py
* refactored file upload feature and re-use it for edting control lists
* added test cases for corpus creation and editing of control lists
> refactored file upload feature and added tests (closes #45)

- app/main/views/dashboard.py
- requirements.txt
> Give read access to control lists when giving access to corpora.

- app/main/views/tokens.py
- app/templates/macros/table_macros.html
- app/templates/macros/tokens_macros.html
- app/templates/main/tokens_search_through_fields.html
I opened a WIP pull request with what I have done so far (in 0.5 days), I have not yet focused on adding tests or generalizing the solution,
* is this how you imagined that the solution should be integrated into the user interface?
* if yes, I have not found other radio buttons / checkboxes in the application, what kind of design would you like for them?
> allow for modifiying sort parameters in user interface

- .travis.yml
Integrated flake8 to the travis CI.
This PR is connected to issue #210
> Integrated flake8 to travis CI

- app/main/views/corpus.py
- app/templates/macros/nav_macros.html
- app/templates/main/control_list_switch.html
Does this solution with a separate view and the drop-down menu for switching control lists meet your expectations? I passed about two thirds of a day on this ticket so far. I intend to add some tests as soon as you confirm me the proposed solution.
> switch control lists

- app/main/views/tokens.py
- app/utils/response.py
- app/utils/tsv.py
First attempt at fixing impossibility to download certain corpora.
> (Export) Attempt at moving from one time download to streaming export

- app/main/views/corpus.py
- app/main/views/tokens.py
- app/models/corpus.py
- app/templates/macros/nav_macros.html
- app/templates/macros/tokens_macros.html
- app/templates/main/corpus_info.html
- app/templates/main/tokens_similar_to_record.html
- app/templates/main/tokens_similar_to_token.html
- app/templates/tei/TEI.xml
- app/templates/tei/geste.xml
When a column (POS, morph, lemma or similar) isn't displayed, then we don't export it and we don't take it into account for stats, history, ...
close: https://github.com/hipster-philology/pyrrha/issues/229
> ignore hidden columns

- app/main/views/tokens.py
- app/models/corpus.py
- app/templates/main/tokens_search_through_fields.html
- tests/db_fixtures/__init__.py
- tests/db_fixtures/floovant.py
- tests/db_fixtures/priapees.py
- tests/db_fixtures/wauchier.py
- tests/test_selenium/base.py
> (Bug) Fixed a bug where search would not work with hidden columns 

- translations/bo_CN/LC_MESSAGES/messages.po
Hello @PonteIneptique, Here are the remaining translated strings of Tibetan. Can you please merge it when you have time. 
Thank you in advance :)
> tibetan-translation

- app/main/filters.py
> Fix #295 ?

- tests/db_fixtures/__init__.py
- correction autoincrémentation controllists id dans db_fixtures._init_
- pb conflit en local d'où branche différente
> Correction conflit debug postgresql

- app/account/forms.py
- tests/test_selenium/test_user_account.py
- création d'un test qui vérifie qu'un même compte est créé indépendant de la case de l'email employé
- création d'un test qui vérifie que l'on peut se log sur un compte qu'importe la case de l'email.
> Création tests account different cases

- app/__init__.py
- app/main/views/tokens.py
- app/templates/main/tokens_search_through_fields.html
- app/utils/forms.py
- tests/test_selenium/base.py
- tests/test_selenium/test_tokens_search_through_fields.py
- Ajout de la possibilité de rechercher dans les tokens d'un corpus avec ou sans case sensitivity. (au niveau de l'app)
- Modification du test raté à cause de la case sensitivity en fonction de ça.
Screen de l'app après cette modification:
> Case sensitive

- app/models/corpus.py
- tests/test_selenium/test_corpus_init.py
Semi résolution de l'issue #190 
- création d'un test qui vérifie que des corpus du même nom chez des utilisateurs différents peuvent coexister.
- Suppression de unique dans corpus name (model)
> Corpus same name

- app/templates/main/tokens_search_through_fields.html
> Add orderBy and desc variables in bottom pages url
